// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "No documentation required for unit testing projects.", Scope = "namespaceanddescendants", Target = "EncoreTickets.SDK.Tests")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1310:Field names should not contain underscore", Justification = "Unit tests need underscores for readability.", Scope = "namespaceanddescendants", Target = "EncoreTickets.SDK.Tests")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "Test case sources can be located in the same file as the testing class.", Scope = "namespaceanddescendants", Target = "EncoreTickets.SDK.Tests")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Regions are useful in test classes and test case sources.", Scope = "namespaceanddescendants", Target = "EncoreTickets.SDK.Tests")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static elements should appear before instance elements", Justification = "Not applicable for test case sources and their respective test classes.", Scope = "namespaceanddescendants", Target = "EncoreTickets.SDK.Tests")]

[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Api.BaseApiTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Api.BaseApiWithAuthenticationTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Api.Results.ApiResultTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Api.Results.Exceptions.ApiExceptionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Api.Results.Exceptions.ContextApiExceptionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Api.Results.Response.ApiResponseTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Api.Utilities.ApiRestClientBuilderTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Authentication.AuthenticationServiceFactoryTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Authentication.JwtAuthenticationServiceTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Authentication.JwtWithApiKeyAuthenticationServiceTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Basket.BasketServiceApiTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Basket.Extensions.ReservationExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Checkout.CheckoutServiceApiTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Content.ContentServiceApiTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Inventory.InventoryServiceApiTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Payment.Extensions.AddressExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Payment.Extensions.OrderExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Payment.Extensions.PaymentExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Payment.Extensions.PaymentMethodExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Payment.Extensions.RefundExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Payment.PaymentServiceApiTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Pricing.PricingServiceApiTestSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Utilities.BaseTypesExtensions.EnumerableExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Utilities.BaseTypesExtensions.EnumExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Utilities.Cache.LazyCacheDecoratorTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Utilities.Cache.MemoryCacheTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Utilities.CommonModels.EntityWithStatusExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Utilities.RestClientWrapper.RestClientWrapperTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Utilities.Serializers.DefaultJsonSerializerTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Venue.Extensions.AttributeExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Venue.Extensions.SeatDetailedExtensionTestsSource")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "Test case sources can have public fields.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Venue.VenueServiceTestsSource")]

[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:'public' members should come before 'private' members", Justification = "Elements should be ordered by access.", Scope = "type", Target = "~T:EncoreTickets.SDK.Tests.UnitTests.Pricing.PricingServiceApiTestSource")]