name: CI

on:
  push:
    branches: [ master, release/*, develop ]
  pull_request:
    branches: [ master, release/*, develop ]

jobs:

  build_dotnet_core:

    name: Test on .NET Core ${{ matrix.dotnet_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet_version: ['2.1.x', '2.2.x', '3.1.x']
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core ${{ matrix.dotnet_version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet_version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal --filter FullyQualifiedName~UnitTests


  build_dotnet_framework:

    name: Test on .NET Framework ${{ matrix.framework_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        framework_version: ['net461']
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Install dependencies
      run: nuget restore EncoreTickets.SDK.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: msbuild EncoreTickets.SDK.sln -p:Configuration=Release

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Test
      run: vstest.console.exe EncoreTickets.SDK.Tests\bin\Release\${{ matrix.framework_version }}\EncoreTickets.SDK.Tests.dll /TestCaseFilter:"FullyQualifiedName~UnitTests"
